# Generated by Django 4.1.13 on 2026-09-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('current_price', models.FloatField()),
                ('predicted_price', models.FloatField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
